// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCacwSoUPG_PE5I72soiBRqrNHfeyh1u30',
    appId: '1:1035984614066:web:af7ea7d14d342bf68a4fab',
    messagingSenderId: '1035984614066',
    projectId: 'walky-423f7',
    authDomain: 'walky-423f7.firebaseapp.com',
    storageBucket: 'walky-423f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDck7XaiqJRZKF7cmnBTjmiJrvxVGosrZg',
    appId: '1:1035984614066:android:af35882f8926e38b8a4fab',
    messagingSenderId: '1035984614066',
    projectId: 'walky-423f7',
    storageBucket: 'walky-423f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGxavyxPQDqyrexoenfJ_NTitWgpTAspc',
    appId: '1:1035984614066:ios:b89718ddce3120968a4fab',
    messagingSenderId: '1035984614066',
    projectId: 'walky-423f7',
    storageBucket: 'walky-423f7.firebasestorage.app',
    iosBundleId: 'com.example.walky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGxavyxPQDqyrexoenfJ_NTitWgpTAspc',
    appId: '1:1035984614066:ios:b89718ddce3120968a4fab',
    messagingSenderId: '1035984614066',
    projectId: 'walky-423f7',
    storageBucket: 'walky-423f7.firebasestorage.app',
    iosBundleId: 'com.example.walky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCacwSoUPG_PE5I72soiBRqrNHfeyh1u30',
    appId: '1:1035984614066:web:44120a499b87ba778a4fab',
    messagingSenderId: '1035984614066',
    projectId: 'walky-423f7',
    authDomain: 'walky-423f7.firebaseapp.com',
    storageBucket: 'walky-423f7.firebasestorage.app',
  );
}
